services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=scrobbled
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    # options to maybe speed up postgresql tests.
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
#  data:
#    driver: local
